# Generated by Django 4.2.2 on 2023-07-03 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=250)),
                ('alt_ext', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('image_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('color_codigo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Madeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cod_Madeira', models.CharField(max_length=10)),
                ('Data_Cadastro', models.DateField()),
                ('Desc_Obs_Madeira', models.CharField(max_length=200)),
                ('Desc_Obs_Ocorrencia', models.CharField(max_length=200)),
                ('Desc_Obs_Nome_Cientifico', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=300)),
                ('detail', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipt.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipt.color')),
            ],
        ),
        migrations.CreateModel(
            name='MadeirasAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipt.madeira')),
            ],
        ),
    ]
