# Generated by Django 4.2.2 on 2023-06-21 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Madeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cod_Madeira', models.CharField(max_length=10)),
                ('Data_Cadastro', models.DateField()),
                ('Desc_Obs_Madeira', models.CharField(max_length=200)),
                ('Desc_Obs_Ocorrência', models.CharField(max_length=200)),
                ('Desc_Obs_Nome_Cientifico', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='MADEIRAS_imgs/')),
                ('detail', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.color')),
            ],
        ),
        migrations.AlterField(
            model_name='madeirasattribute',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.madeira'),
        ),
        migrations.DeleteModel(
            name='Madeiras',
        ),
    ]
