# Generated by Django 4.2.2 on 2023-07-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_madeira_alter_madeirasattribute_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='madeirasattribute',
            old_name='title',
            new_name='madeira',
        ),
    ]
