# Generated by Django 4.2.2 on 2023-07-17 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_conteudo_especie_genero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='madeirasattribute',
            name='madeira',
        ),
        migrations.DeleteModel(
            name='Madeira',
        ),
        migrations.DeleteModel(
            name='MadeirasAttribute',
        ),
    ]
