# Generated by Django 4.2.2 on 2023-07-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_madeirasattribute_madeira_delete_madeira_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOcorrencia',
            fields=[
                ('cod_tipo_ocorrencia', models.AutoField(db_column='Cod_Tipo_Ocorrencia', primary_key=True, serialize=False)),
                ('desc_tipo_ocorrencia', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Desc_Tipo_Ocorrencia', max_length=80, null=True)),
            ],
            options={
                'db_table': 'Tipo_Ocorrencia',
                'managed': False,
            },
        ),
    ]
