# Generated by Django 4.2.2 on 2023-07-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tipoocorrencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Latin1_General_CI_AS', max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='Latin1_General_CI_AS', max_length=255)),
                ('codename', models.CharField(db_collation='Latin1_General_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(db_collation='Latin1_General_CI_AS', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(db_collation='Latin1_General_CI_AS', max_length=150, unique=True)),
                ('first_name', models.CharField(db_collation='Latin1_General_CI_AS', max_length=150)),
                ('last_name', models.CharField(db_collation='Latin1_General_CI_AS', max_length=150)),
                ('email', models.CharField(db_collation='Latin1_General_CI_AS', max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Determinador',
            fields=[
                ('cod_determinador', models.AutoField(db_column='Cod_Determinador', primary_key=True, serialize=False)),
                ('nome_determinador', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Nome_Determinador', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Determinador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, db_collation='Latin1_General_CI_AS', null=True)),
                ('object_repr', models.CharField(db_collation='Latin1_General_CI_AS', max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField(db_collation='Latin1_General_CI_AS')),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_collation='Latin1_General_CI_AS', max_length=100)),
                ('model', models.CharField(db_collation='Latin1_General_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(db_collation='Latin1_General_CI_AS', max_length=255)),
                ('name', models.CharField(db_collation='Latin1_General_CI_AS', max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(db_collation='Latin1_General_CI_AS', max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(db_collation='Latin1_General_CI_AS')),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('cod_familia', models.AutoField(db_column='Cod_Familia', primary_key=True, serialize=False)),
                ('nome_familia', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Nome_Familia', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Familia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fonte',
            fields=[
                ('cod_fonte', models.AutoField(db_column='Cod_Fonte', primary_key=True, serialize=False)),
                ('cod_referencia', models.IntegerField(blank=True, db_column='Cod_Referencia', null=True)),
                ('desc_num_fonte', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Desc_Num_Fonte', max_length=50, null=True)),
                ('desc_obs_fonte', models.TextField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Desc_Obs_Fonte', null=True)),
            ],
            options={
                'db_table': 'Fonte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('cod_item', models.AutoField(db_column='Cod_Item', primary_key=True, serialize=False)),
                ('nome_item', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Nome_Item', max_length=200, null=True)),
                ('cod_item_pai', models.IntegerField(blank=True, db_column='Cod_Item_Pai', null=True)),
                ('cod_nivel_item', models.IntegerField(blank=True, db_column='Cod_Nivel_Item', null=True)),
                ('cod_tipo_item', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Cod_Tipo_Item', max_length=3, null=True)),
                ('num_parte_inteira', models.DecimalField(blank=True, db_column='Num_Parte_Inteira', decimal_places=0, max_digits=8, null=True)),
                ('num_parte_decimal', models.DecimalField(blank=True, db_column='Num_Parte_Decimal', decimal_places=0, max_digits=2, null=True)),
                ('desc_unidade_medida', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Desc_Unidade_Medida', max_length=50, null=True)),
                ('ind_exibir_ficha', models.IntegerField(blank=True, db_column='Ind_Exibir_Ficha', null=True)),
                ('cod_tipo_pesquisa', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Cod_Tipo_Pesquisa', max_length=3, null=True)),
                ('num_ordem_item', models.IntegerField(blank=True, db_column='Num_Ordem_Item', null=True)),
                ('desc_obs_item', models.TextField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Desc_Obs_Item', null=True)),
                ('cod_status_item', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Cod_Status_Item', max_length=1, null=True)),
                ('ind_exibir_pesquisa', models.IntegerField(blank=True, db_column='Ind_Exibir_Pesquisa', null=True)),
                ('cod_tipo_parametro', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Cod_Tipo_Parametro', max_length=3, null=True)),
            ],
            options={
                'db_table': 'Item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemConteudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_item', models.IntegerField(db_column='Cod_Item')),
                ('cod_conteudo', models.IntegerField(db_column='Cod_Conteudo')),
            ],
            options={
                'db_table': 'Item_Conteudo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Madeira',
            fields=[
                ('cod_madeira', models.AutoField(db_column='Cod_Madeira', primary_key=True, serialize=False)),
                ('data_cadastro', models.DateField(blank=True, db_column='Data_Cadastro', null=True)),
                ('desc_obs_madeira', models.TextField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Desc_Obs_Madeira', null=True)),
                ('desc_obs_ocorrencia', models.TextField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Desc_Obs_Ocorrencia', null=True)),
                ('desc_obs_nome_cientifico', models.TextField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Desc_Obs_Nome_Cientifico', null=True)),
                ('cod_status_madeira', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Cod_Status_Madeira', max_length=1, null=True)),
            ],
            options={
                'db_table': 'Madeira',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MadeiraFoto',
            fields=[
                ('cod_madeira', models.IntegerField(db_column='Cod_Madeira', primary_key=True, serialize=False)),
                ('cod_foto', models.IntegerField(db_column='Cod_Foto')),
                ('nome_arquivo_foto', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Nome_Arquivo_Foto', max_length=100, null=True)),
                ('cod_tipo_foto', models.IntegerField(blank=True, db_column='Cod_Tipo_Foto', null=True)),
                ('desc_obs_foto', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Desc_Obs_Foto', max_length=200, null=True)),
                ('nome_arquivo_zoom', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Nome_Arquivo_Zoom', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Madeira_Foto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MadeiraItem',
            fields=[
                ('cod_madeira', models.IntegerField(db_column='Cod_Madeira', primary_key=True, serialize=False)),
                ('cod_item', models.IntegerField(db_column='Cod_Item')),
                ('num_linha', models.IntegerField(db_column='Num_Linha')),
                ('desc_item', models.TextField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Desc_Item', null=True)),
                ('valor_inteiro', models.DecimalField(blank=True, db_column='Valor_Inteiro', decimal_places=0, max_digits=8, null=True)),
                ('valor_decimal', models.DecimalField(blank=True, db_column='Valor_Decimal', decimal_places=0, max_digits=2, null=True)),
                ('cod_conteudo', models.IntegerField(blank=True, db_column='Cod_Conteudo', null=True)),
            ],
            options={
                'db_table': 'Madeira_Item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MadeiraItemFonte',
            fields=[
                ('cod_madeira', models.IntegerField(db_column='Cod_Madeira', primary_key=True, serialize=False)),
                ('cod_item', models.IntegerField(db_column='Cod_Item')),
                ('num_linha', models.IntegerField(db_column='Num_Linha')),
                ('num_ordem_fonte', models.IntegerField(db_column='Num_Ordem_Fonte')),
                ('cod_fonte', models.IntegerField(blank=True, db_column='Cod_Fonte', null=True)),
            ],
            options={
                'db_table': 'Madeira_Item_Fonte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MadeiraItemObservacao',
            fields=[
                ('cod_madeira', models.IntegerField(db_column='Cod_Madeira', primary_key=True, serialize=False)),
                ('cod_item', models.IntegerField(db_column='Cod_Item')),
                ('num_linha', models.IntegerField(db_column='Num_Linha')),
                ('num_obs', models.IntegerField(db_column='Num_Obs')),
                ('desc_obs', models.TextField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Desc_Obs', null=True)),
            ],
            options={
                'db_table': 'Madeira_Item_Observacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MadeiraItemObsFonte',
            fields=[
                ('cod_madeira', models.IntegerField(db_column='Cod_Madeira', primary_key=True, serialize=False)),
                ('cod_item', models.IntegerField(db_column='Cod_Item')),
                ('num_linha', models.IntegerField(db_column='Num_Linha')),
                ('num_obs', models.IntegerField(db_column='Num_Obs')),
                ('num_ordem_fonte', models.IntegerField(db_column='Num_Ordem_Fonte')),
                ('cod_fonte', models.IntegerField(blank=True, db_column='Cod_Fonte', null=True)),
            ],
            options={
                'db_table': 'Madeira_Item_Obs_Fonte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MadeiraNomeCientifico',
            fields=[
                ('cod_madeira', models.AutoField(db_column='Cod_Madeira', primary_key=True, serialize=False)),
                ('cod_nome_cientifico', models.IntegerField(db_column='Cod_Nome_Cientifico')),
                ('cod_familia', models.IntegerField(blank=True, db_column='Cod_Familia', null=True)),
                ('cod_genero', models.IntegerField(blank=True, db_column='Cod_Genero', null=True)),
                ('cod_especie', models.IntegerField(blank=True, db_column='Cod_Especie', null=True)),
                ('cod_determinador', models.IntegerField(blank=True, db_column='Cod_Determinador', null=True)),
            ],
            options={
                'db_table': 'Madeira_Nome_Cientifico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MadeiraNomeInternacional',
            fields=[
                ('cod_madeira', models.IntegerField(db_column='Cod_Madeira', primary_key=True, serialize=False)),
                ('cod_nome_internacional', models.IntegerField(db_column='Cod_Nome_Internacional')),
                ('nome_internacional', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Nome_Internacional', max_length=80, null=True)),
            ],
            options={
                'db_table': 'Madeira_Nome_Internacional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MadeiraNomeInternFonte',
            fields=[
                ('cod_madeira', models.IntegerField(db_column='Cod_Madeira', primary_key=True, serialize=False)),
                ('cod_nome_internacional', models.IntegerField(db_column='Cod_Nome_Internacional')),
                ('num_ordem_fonte', models.IntegerField(db_column='Num_Ordem_Fonte')),
                ('cod_fonte', models.IntegerField(blank=True, db_column='Cod_Fonte', null=True)),
            ],
            options={
                'db_table': 'Madeira_Nome_Intern_Fonte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MadeiraNomeInternOcorr',
            fields=[
                ('cod_madeira', models.IntegerField(db_column='Cod_Madeira', primary_key=True, serialize=False)),
                ('cod_nome_internacional', models.IntegerField(db_column='Cod_Nome_Internacional')),
                ('cod_ocorrencia', models.IntegerField(db_column='Cod_Ocorrencia')),
            ],
            options={
                'db_table': 'Madeira_Nome_Intern_Ocorr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MadeiraNomePopular',
            fields=[
                ('cod_madeira', models.IntegerField(db_column='Cod_Madeira', primary_key=True, serialize=False)),
                ('cod_nome_popular', models.IntegerField(db_column='Cod_Nome_Popular')),
                ('nome_popular', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Nome_Popular', max_length=100, null=True)),
                ('ind_nome_principal', models.IntegerField(blank=True, db_column='Ind_Nome_Principal', null=True)),
            ],
            options={
                'db_table': 'Madeira_Nome_Popular',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MadeiraOcorrencia',
            fields=[
                ('cod_madeira', models.IntegerField(db_column='Cod_Madeira', primary_key=True, serialize=False)),
                ('cod_ocorrencia', models.IntegerField(db_column='Cod_Ocorrencia')),
            ],
            options={
                'db_table': 'Madeira_Ocorrencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('cod_ocorrencia', models.AutoField(primary_key=True, serialize=False)),
                ('nome_ocorrencia', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Nome_Ocorrencia', max_length=80, null=True)),
                ('cod_tipo_ocorrencia', models.IntegerField(blank=True, db_column='Cod_Tipo_Ocorrencia', null=True)),
                ('cod_origem', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Cod_Origem', max_length=1, null=True)),
            ],
            options={
                'db_table': 'Ocorrencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('cod_referencia', models.AutoField(db_column='Cod_Referencia', primary_key=True, serialize=False)),
                ('nome_referencia', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Nome_Referencia', max_length=50, null=True)),
                ('nome_completo_referencia', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Nome_Completo_Referencia', max_length=150, null=True)),
                ('desc_endereco_site', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Desc_Endereco_Site', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Referencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoFoto',
            fields=[
                ('cod_tipo_foto', models.AutoField(db_column='Cod_Tipo_Foto', primary_key=True, serialize=False)),
                ('desc_tipo_foto', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Desc_Tipo_Foto', max_length=100, null=True)),
                ('num_ordem_tipo_foto', models.IntegerField(blank=True, db_column='Num_Ordem_Tipo_Foto', null=True)),
            ],
            options={
                'db_table': 'Tipo_Foto',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.AlterModelOptions(
            name='conteudo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='especie',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'managed': False},
        ),
    ]
