# Generated by Django 4.2.2 on 2023-08-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Madeira',
            fields=[
                ('cod_madeira', models.IntegerField(db_column='Cod_Madeira', primary_key=True, serialize=False)),
                ('cod_nome_popular', models.IntegerField(db_column='Cod_Nome_Popular')),
                ('nome_popular', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Nome_Popular', max_length=100, null=True)),
                ('ind_nome_principal', models.IntegerField(blank=True, db_column='Ind_Nome_Principal', null=True)),
            ],
            options={
                'db_table': 'Madeira_Nome_Popular',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nome_Popular',
            fields=[
                ('cod_nome_popular', models.IntegerField(db_column='Cod_Nome_Popular', primary_key=True, serialize=False)),
                ('nome_popular', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='Nome_Popular', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Nome_Popular',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Person_Madeira',
                'managed': False,
            },
        ),
    ]
